FROM arm64v8/debian:stretch-slim

ARG CMAKE_VERSION=3.15.3

WORKDIR /tmp

RUN apt update && \
    apt install -y build-essential ca-certificates wget curl git && \
    apt clean && \
    wget https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION.tar.gz && \
    tar zxvf cmake-$CMAKE_VERSION.tar.gz && \
    cd cmake-$CMAKE_VERSION && \
    ./bootstrap --parallel=$(nproc) && \
    make -j$(nproc) && \
    make install && \
    cd /tmp && rm -rf *
